# These are supported funding model platforms

# GitHub Sponsors
# github: [narek589]

# Open Collective
# open_collective: ino-icon-maker

# Buy Me a Coffee
# ko_fi: narek589

# Patreon
# patreon: narek589

# Custom URL
# custom: https://www.buymeacoffee.com/narek589

# Uncomment and add your preferred funding platforms above

